# Generated by Django 4.2.4 on 2023-09-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_serviceimages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="name",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="services",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
